export const CARDS_FETCH = "CARDS_FETCH";
export const CARDS_FETCH_FAILED = "CARDS_FETCH_FAILED";
export const CARDS_FETCH_SUCCESS = "CARDS_FETCH_SUCCESS";
export const CARDS_FETCH_MORE = "CARDS_FETCH_MORE";
export const CARDS_FETCH_MORE_FAILED = "CARDS_FETCH_MORE_FAILED";
export const CARDS_FETCH_MORE_SUCCESS = "CARDS_FETCH_MORE_SUCCESS";
export const INCREMENT_PAGE = "INCREMENT_PAGE";
export const DECREMENT_PAGE = "DECREMENT_PAGE";
